version: "3"

services:
  database:
    container_name: db
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - ./dbfiles/so2021.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

volumes:
  db:
