version: "3"

services:
  extractor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST:-172.26.234.192}
    depends_on:
      - database

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_NAME:-dictionary}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./dbfiles/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

volumes:
  db:
